### ISSUE TITLE
sane logging

### ISSUE THREAD

**Issue by dm03514** [dm03514/func-y-task-engine#12]
There are a couple parsing errors that don't provide enough context because of dynamic loading,  these need to have enough context to be able to go to the exact file that caused it.  

if a task directive doesn't have all the correct kwargs for an event, it will cause this

**Comment by dm03514** [comment]
Create a task with invalid event syntax, it should result in an error with the params it is attempting to instantiate the `Event` with

**Comment by dm03514** [comment]
Meaningful isnt' really validated right now, while no one is using it.

The errors can be tracked down by checking out the stack trace and source code.  It is definitely sub optimal, but I don't think a validation framework is going to be a trivial amount of work.  Instead of laying the foundation for usability for users whom don't exist yet, initial users are going to have to hunt down the errors themselves:(

```
    def test_invalid_event_shows_meaningful_error(self):
        TEST = """
---
events:
  - name: invalid
    event_fulfillment_strategy:
      type: nsq.NSQStreamingFulfillment
      channel1: test
    transition_conditions:
        - type: invalid
max_timeout: 2000
name: Invalid task
version: "1"
        """
        state_dict = yaml.load(TEST)
        machine = TaskMachine(machine_dict=state_dict)
        self.assertEqual(machine.state, STATES.PENDING)
```
produces:

```
ipdb> c
E
======================================================================
ERROR: test_invalid_event_shows_meaningful_error (tests.unit.machine.test_parsing_errors.ParsingErrorsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant_data/func-y-task-engine/tests/unit/machine/test_parsing_errors.py", line 26, in test_invalid_event_shows_meaningful_error
    machine = TaskMachine(machine_dict=state_dict)
  File "/vagrant_data/func-y-task-engine/funcytaskengine/machine.py", line 87, in __init__
    self.events = Events([Event(**e) for e in machine_dict['events']])
  File "/vagrant_data/func-y-task-engine/funcytaskengine/machine.py", line 39, in __init__
    self.fulfillment = EventFulfillmentFactory.build(event_fulfillment_strategy)
  File "/vagrant_data/func-y-task-engine/funcytaskengine/parsers/loaders.py", line 41, in build
    return DynamicClass(**test_config)
TypeError: __init__() got an unexpected keyword argument 'channel1'

----------------------------------------------------------------------
Ran 1 test in 84.381s

FAILED (errors=1)
```
