### ISSUE TITLE
Way better assertions, failure shouldn't be the top level assertion but should be informative

### ISSUE THREAD

**Issue by dm03514** [dm03514/func-y-task-engine#50]
```
2017-11-28 19:23:52,045 - funcytaskengine.engine - DEBUG - {'message': 'task_failure'}
Traceback (most recent call last):
  File "/usr/local/bin/funcy-task-engine.py", line 4, in <module>
    __import__('pkg_resources').run_script('funcy-task-engine==0.0.1.dev0', 'funcy-task-engine.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/funcy_task_engine-0.0.1.dev0-py2.7.egg/EGG-INFO/scripts/funcy-task-engine.py", line 49, in <module>

  File "/usr/local/lib/python2.7/site-packages/funcy_task_engine-0.0.1.dev0-py2.7.egg/EGG-INFO/scripts/funcy-task-engine.py", line 13, in run

  File "build/bdist.linux-x86_64/egg/funcytaskengine/unittesttaskexecutor.py", line 114, in run
  File "build/bdist.linux-x86_64/egg/funcytaskengine/unittesttaskexecutor.py", line 49, in test_individual
AssertionError
```

This needs to be useful

**Comment by dm03514** [comment]
Augmented the meaningless top level assertion with the machine error (if any):

```
2017-12-05 01:57:52,866 - funcytaskengine.machine - ERROR - {'event_name': 'google_request', 'message': 'event_execution_error', 'exception': AssertionError('300 != 200',)}
2017-12-05 01:57:52,881 - funcytaskengine.machine - ERROR - Traceback (most recent call last):
  File "/vagrant_data/func-y-task-engine/funcytaskengine/machine.py", line 92, in run
    result = event.execute(event_results=self.event_results)
  File "/vagrant_data/func-y-task-engine/funcytaskengine/machine.py", line 52, in execute
    result = self.fulfillment.run(self.initiator, self.conditions, **kwargs)
  File "/vagrant_data/func-y-task-engine/funcytaskengine/event_fulfillment/poll.py", line 45, in run
    conditions.apply()
  File "/vagrant_data/func-y-task-engine/funcytaskengine/transition_conditions/__init__.py", line 58, in apply
    self.vs = con.apply(self.vs)
  File "/vagrant_data/func-y-task-engine/funcytaskengine/transition_conditions/assertions.py", line 86, in apply
    assert self.to_equal == to_assert, '{} != {}'.format(self.to_equal, to_assert)
AssertionError: 300 != 200

2017-12-05 01:57:52,881 - funcytaskengine.engine - DEBUG - {'message': 'task_failure'}
Traceback (most recent call last):
  File "bin/funcy-task-engine.py", line 49, in <module>
    args.func(args)
  File "bin/funcy-task-engine.py", line 13, in run
    te.run()
  File "/vagrant_data/func-y-task-engine/funcytaskengine/unittesttaskexecutor.py", line 114, in run
    test_individual(test_file)
  File "/vagrant_data/func-y-task-engine/funcytaskengine/unittesttaskexecutor.py", line 49, in test_individual
    assert result
AssertionError****
```

**Comment by dm03514** [comment]
we'll be able to add json logger later , if necessary:

```
        'json': {
            'format': DEFAULT_LOG_FORMAT,
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        },
```
